# Generated by Django 5.0.4 on 2024-04-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платёж', 'verbose_name_plural': 'платежи'},
        ),
    ]
