# Generated by Django 5.0.4 on 2024-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='deposit',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('наличными', 'наличными'), ('переводом', 'переводом')], max_length=9, verbose_name='способ оплаты'),
        ),
    ]
