# Generated by Django 5.0.4 on 2024-05-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='стоимость урока'),
        ),
    ]
