# Generated by Django 5.0.4 on 2024-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0005_course_price_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='стоимость курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='стоимость урока'),
        ),
    ]
