# Generated by Django 5.0.4 on 2024-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0006_alter_course_price_alter_lesson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=50000, verbose_name='стоимость курса'),
        ),
    ]
