# Generated by Django 5.0.4 on 2024-05-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying', '0007_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
